"""Codegen handler -- assembles master_analysis.R from individual analysis outputs."""
from __future__ import annotations
import argparse, sys, json, os
from pathlib import Path
from datetime import datetime
from typing import List, Optional

def _read_summary(dir_path: Path) -> dict:
    """Read 5_summary.json from a result directory."""
    sf = dir_path / "5_summary.json"
    if sf.is_file():
        return json.loads(sf.read_text(encoding="utf-8"))
    return {}

def _read_code(dir_path: Path) -> str:
    """Read 6_analysis_code.R, stripping shebang and deduplicating libraries."""
    cf = dir_path / "6_analysis_code.R"
    if not cf.is_file():
        return ""
    lines = cf.read_text(encoding="utf-8").split("\n")
    # Strip shebang and timestamp comments
    clean = []
    skip_header = True
    seen_libraries = set()
    for line in lines:
        stripped = line.strip()
        if skip_header:
            if stripped.startswith("#!") or stripped.startswith("# Generated") or stripped == "":
                continue
            skip_header = False
        # Skip library calls that will be in the master header
        if stripped.startswith("library(") or stripped.startswith("suppressPackageStartupMessages"):
            lib_name = stripped.replace("library(", "").replace(")", "").replace(";", "").strip().strip('"').strip("'")
            if lib_name in seen_libraries:
                continue
            seen_libraries.add(lib_name)
        clean.append(line)
    return "\n".join(clean)

def _collect_libraries_from_code(code: str) -> list:
    """Extract unique library names from R code."""
    libs = set()
    import re
    for m in re.finditer(r'library\(([^)]+)\)', code):
        for lib in m.group(1).split(";"):
            lib = lib.strip().strip('"').strip("'")
            if lib and lib != "DESeq2" and lib != "limma":
                libs.add(lib)
    return sorted(libs)

def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="BioSherpa Codegen -- Master Analysis Script Generator")
    parser.add_argument("--diffexp-dir", type=str, default="", help="Diffexp output directory")
    parser.add_argument("--enrichment-dir", type=str, default="", help="Enrichment output directory")
    parser.add_argument("--pubmed-dir", type=str, default="", help="PubMed output directory (optional)")
    parser.add_argument("--output-dir", type=str, required=True, help="Output directory for master script")
    args = parser.parse_args(argv)

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    sections = []
    all_libraries = set()

    # Header
    sections.append("""#!/usr/bin/env Rscript
# ============================================================================
# Master Analysis Script -- generated by BioSherpa Codegen Agent
# Generated: %s
#
# This script reproduces the complete analysis pipeline.
# Run: Rscript master_analysis.R
# ============================================================================
""" % now)

    # --- Diffexp section ---
    de_dir = Path(args.diffexp_dir) if args.diffexp_dir else None
    if de_dir and de_dir.is_dir():
        summary = _read_summary(de_dir)
        code = _read_code(de_dir)
        
        sections.append("# ============================================================================")
        sections.append("# 1. Differential Expression Analysis (%s)" % summary.get("method", "N/A"))
        sections.append("# ============================================================================")
        sections.append("")
        sections.append("# --- Parameters ---")
        for k in ["method", "treatment", "control", "design", "pvalue_cutoff", "lfc_threshold"]:
            if k in summary:
                sections.append("%s <- %s" % (k, json.dumps(summary[k])))
        sections.append("de_dir <- %s" % json.dumps(str(de_dir.resolve())))
        sections.append("")
        
        if code.strip():
            # Extract pure analysis code (skip parameter section, just keep analysis)
            sections.append(code.strip())
        else:
            sections.append("# (No reproducible code found in diffexp output)")
        
        # Collect libraries
        for lib in _collect_libraries_from_code(code):
            all_libraries.add(lib)
        sections.append("")

    # --- Enrichment section ---
    en_dir = Path(args.enrichment_dir) if args.enrichment_dir else None
    if en_dir and en_dir.is_dir():
        summary = _read_summary(en_dir)
        code = _read_code(en_dir)
        
        sections.append("# ============================================================================")
        sections.append("# 2. GO/KEGG Enrichment Analysis")
        sections.append("# ============================================================================")
        sections.append("")
        sections.append("# --- Parameters ---")
        for k in ["organism", "pvalue_cutoff", "qvalue_cutoff"]:
            if k in summary:
                sections.append("%s <- %s" % (k, json.dumps(summary[k])))
        sections.append("en_dir <- %s" % json.dumps(str(en_dir.resolve())))
        sections.append("")
        
        if code.strip():
            sections.append(code.strip())
        else:
            sections.append("# (No reproducible code found in enrichment output)")
        
        for lib in _collect_libraries_from_code(code):
            all_libraries.add(lib)
        sections.append("")

    # --- PubMed section ---
    pm_dir = Path(args.pubmed_dir) if args.pubmed_dir else None
    if pm_dir and pm_dir.is_dir():
        summary = _read_summary(pm_dir)
        code = _read_code(pm_dir)
        
        sections.append("# ============================================================================")
        sections.append("# 3. PubMed Literature Search")
        sections.append("# ============================================================================")
        sections.append("")
        if code.strip():
            sections.append(code.strip())
        else:
            sections.append("# (PubMed search was run -- see pubmed_results.csv in output)")
        sections.append("")

    # --- Footer ---
    sections.append("# ============================================================================")
    sections.append("cat('\nMaster analysis complete. Results saved to respective directories.\n')")

    # Insert library declarations after header
    master = "\n".join(sections)
    
    # Build library block
    lib_block = []
    if all_libraries:
        lib_block.append("\n# --- Required libraries ---")
        lib_block.append("suppressPackageStartupMessages({")
        for lib in sorted(all_libraries):
            lib_block.append("  library(%s)" % lib)
        lib_block.append("})")
        lib_block.append("")
        # Insert after header line (after the === line)
        header_end = master.find("# ============================================================================\n", master.find("Generated:"))
        if header_end > 0:
            header_end = master.find("\n", header_end) + 1
            master = master[:header_end] + "\n" + "\n".join(lib_block) + "\n" + master[header_end:]

    master_path = out / "master_analysis.R"
    master_path.write_text(master, encoding="utf-8")
    print(f"Master script written to: {master_path}")
    print(f"Size: {master_path.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())